import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

import Container from 'react-bootstrap/Container';
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';

import Nav from 'react-bootstrap/Nav';
import Navbar from 'react-bootstrap/Navbar';
import NavDropdown from 'react-bootstrap/NavDropdown';


import Tab from 'react-bootstrap/Tab';


import Script from 'next/script'
 
// export default function Dashboard() {
//   return (
//     <>
//       <Script src="https://example.com/script.js" />
//     </>
//   )
// }



const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>


      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Navbar collapseOnSelect expand="lg" className="bg-body-tertiary fixed-top cChoreoNav">
        <Container>
          <Navbar.Brand href="/"><img src="https://wso2.cachefly.net/wso2/sites/all/2020-theme/images/choreo-logo-black.svg" /></Navbar.Brand>
          <Navbar.Toggle aria-controls="responsive-navbar-nav" />
          <Navbar.Collapse id="responsive-navbar-nav">
            <Nav className="me-auto">

            </Nav>
            <Nav>
              <Nav.Link href="#deets">More deets</Nav.Link>
              <Nav.Link eventKey={2} href="#memes">
                Dank memes
              </Nav.Link>
              <Nav.Link href="#features">Features</Nav.Link>
              <Nav.Link href="#pricing">Pricing</Nav.Link>
              <NavDropdown title="Dropdown" id="collapsible-nav-dropdown">
                <NavDropdown.Item href="#action/3.1">Action</NavDropdown.Item>
                <NavDropdown.Item href="#action/3.2">
                  Another action
                </NavDropdown.Item>
                <NavDropdown.Item href="#action/3.3">Something</NavDropdown.Item>
                <NavDropdown.Divider />
                <NavDropdown.Item href="#action/3.4">
                  Separated link
                </NavDropdown.Item>
              </NavDropdown>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>





      <div className="cIntro cGrayBackground">
        <Container>
          <Row>
            <Col sm={12} md={6}>
              <h1>Just write the code, <br /> we do the rest</h1>
              <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
            </Col>
            <Col sm={12} md={2}>&nbsp;</Col>
            <Col sm={12} md={4}></Col>
          </Row>


        </Container>

      </div>

      <div className="cSection cWhiteBG">
       
     
      <Container>
     <Row>
        <div className="col-sm-12 col-md-12 col-lg-12">
          <div className="cSuppport">
            <h2>Resource Cost Estimation</h2>
          </div>
        </div>
        <div className="col-sm-12 col-md-4 col-lg-4">&nbsp;</div>
        <div className="col-sm-12 col-md-4 col-lg-4">
          <div className="cTabCOntrolContainer ">
            <ul className="nav nav-pills mb-3" id="pills-tab" role="tablist">
              <li className="nav-item">
                <a className="nav-link cPricingTabs cRightButton active" id="monthly" data-toggle="pill" href="" role="tab" aria-controls="pills-home" aria-selected="true" aria-label="Monthly">Monthly</a>
              </li>
              <li className="nav-item">
                <a className="nav-link cPricingTabs cLeftButton" id="hourly" data-toggle="pill" href="" role="tab" aria-controls="pills-profile" aria-selected="false" aria-label="Hourly">Hourly</a>
              </li>
            </ul>
          </div>
        </div>
        <div className="col-sm-12 col-md-4 col-lg-4">&nbsp;</div>
        <div className="col-sm-12 col-md-12 col-lg-12">
          <div className="cPriceCol tab-content" id="pills-tabContent">
            <div className="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
              <div className="col-sm-12 col-md-4 col-lg-4">&nbsp;</div>
              <div className="col-sm-12 col-md-4 col-lg-4 cTextAlignCenter cTopTotalCost">
                <span className="cSubTotalTitle" id="total_cost_lable">Total Cost</span>
                <span className="b2cBasic" id="total_cost_amount">$0.00</span>
                <span className="cSubTotalTitle" id="required_more" >If you require more <a href="/contact/?ref=choreopricing" aria-label="contact us">contact us</a>.</span>
              </div>
              <div className="col-sm-12 col-md-4 col-lg-4">&nbsp;</div>
              <div className="clearfix"></div>
              <div className="col-sm-12 col-md-8 col-lg-8 cSpLine">
                <div className="colwrap cRightCol">
  
  
                  <div className="col-sm-12 col-md-4 col-lg-4 cSmallCol">
                    <div className="cSliderContainer">
                      <label>CPU</label>
                      <div className="cSlider">
                        <div id="memory-slider" className="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all ui-slider-float"><div className="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" ></div><span className="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" ><span className="ui-slider-tip">0.0</span></span></div>
                      </div>
                    </div>
                  </div>
  
                  <div className="col-sm-12 col-md-4 col-lg-4 cSmallCol">
                    <div className="cSliderContainer">
                      <label>RAM</label>
                      <div className="cSlider">
                        <div id="memory-slider2" className="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all ui-slider-float"><div className="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min"></div><span className="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" ><span className="ui-slider-tip">0.0</span></span></div>
                      </div>
                    </div>
                  </div>
  
                  <div className="col-sm-12 col-md-4 col-lg-4 cSmallCol">
                    <div className="cSliderContainer">
                      <label>Storage</label>
                      <div className="cSlider">
                        <div id="memory-slider4" className="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all ui-slider-float"><div className="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min"></div><span className="ui-slider-handle ui-state-default ui-corner-all" tabindex="0"><span className="ui-slider-tip">0</span></span></div>
                      </div>
                    </div>
                  </div>
                  <div className="col-sm-12 col-md-12 col-lg-12 cSmallCol">
                    <div className="cSliderContainer">
                      <label>Network Egress</label>
                      <div className="cSlider">
                        <div id="memory-slider3" className="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all ui-slider-float"><div className="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min" ></div><span className="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" ><span className="ui-slider-tip">0</span></span></div>
                      </div>
                    </div>
                  </div>
                  <div className="cTextAlignCenter cSubTotals" id="resource_cost_section">
                    <span className="cSubTotalTitle">Resource Cost</span>
                    <span className="b2cBasic" id="resource_cost_amount">$0.00</span>
                  </div>
                </div>
              </div>
              <div className="col-sm-12 col-md-4 col-lg-4">
                <div className="colwrap cLeftCol">
                  <div className="cSliderContainer">
                    <div className="form__group">
                      <div className="form__radio-group">
                        <ul className="cRadioUL">
                          <li>
                            <input type="radio" name="component_options" id="developer" value="developer" className="form__radio-input" checked="checked"/>
                            <label className="form__label-radio" for="developer">
                              <span className="form__radio-button"></span>Developer
                            </label>
                          </li>
                          <li>
                            <input type="radio" name="component_options" id="payg" value="payg" className="form__radio-input"/>
                            <label className="form__label-radio" for="payg">
                              <span className="form__radio-button"></span> PAYG
                            </label>
                          </li>
                        </ul>
                      </div>
                    </div>
                  </div>
  
                  <div className="cSliderContainer">
                    <label>Components</label>
                    <div className="cSlider">
                      <div id="memory-slider5" className="ui-slider ui-slider-horizontal ui-widget ui-widget-content ui-corner-all ui-slider-float"><div className="ui-slider-range ui-widget-header ui-corner-all ui-slider-range-min"></div><span className="ui-slider-handle ui-state-default ui-corner-all" tabindex="0" ><span className="ui-slider-tip">0</span></span></div>
                    </div>
                  </div>
                  <div className="cTextAlignCenter cSubTotals" id="component_cost_section">
                    <span className="cSubTotalTitle">Component Cost</span>
                    <span className="b2cBasic" id="component_cost_amount">$0.00</span>
                  </div>
                </div>
              </div>
            </div>
  
          </div>
        </div>
    </Row>
    </Container>

      </div>




        






      <main className={`${styles.main} ${inter.className}`}>


        {/* <div className={styles.cTest}>madhura</div> */}











        <div className={styles.description}>
          <p className="madhura">
            Get started by editing&nbsp;xxxxxxxxx
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
